name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Make files executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run:  export _JAVA_OPTIONS="-Xms4000m -Xmx8000m" 
          ./gradlew :converter:build
